### PR TITLE
adapt code to work with Harmony Hub v4.15.250

### PR DESCRIPTION
**Pull request by foxriver76**
- es8 is tested
- es6 not ;-)

### CODE REVIEW

**Comment by foxriver76** [comment]
Oh, code still needs adaption for ``requestActivityChange`` missed that

**Comment by Pmant** [comment]
does this work for now? we need a fast workaround, even if its not perfect.

**Comment by foxriver76** [comment]
Yes but maybe due to the fact that activityChange is now a websocket call we would have to wait via an on listener for the correct message and this would be an awful implementation. So it would make more sense to handle the hubBlocked until answer is there logic in the iobroker Adapter code .

**Comment by foxriver76** [comment]
But basically everything works I am using it as it is since I opened the PR

**Comment by Pmant** [comment]
Okay ty so far, will look into it later. 
I'm really busy atm, could you do me a favor and update the adapter to force use of this version (1.0.5)?

**Pull request merged**
